[ADD] Bookpage 구현
wecode-bootcamp-korea/27-2nd-ReadyBooks-backend pull request #12
Opened 2021-12-16 09:41 UTC by jincastle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- bookpage 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. bookpage 필요한 정보 전달

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2021-12-20 03:16 UTC, lordmyshepherd requested changes

2021-12-20 03:16 UTC, lordmyshepherd commented on users/tests.py
> +#                     "id":114142,
주석 처리된 코드는 확인 후에 수정해주세요!

2021-12-20 03:16 UTC, lordmyshepherd commented on books/tests.py
> +TestCase.maxDiff = None
필요한 코드인가요?

2021-12-20 03:16 UTC, lordmyshepherd requested changes

2021-12-20 03:16 UTC, lordmyshepherd commented on books/views.py
> +            JsonResponse({"message" : "TYPE_ERROR"}, status=401)
로직 깔끔하네요! 👍🏻

2021-12-20 04:05 UTC, jincastle commented on users/tests.py
> +#                     "id":114142,
넵 수정했습니다

2021-12-20 04:06 UTC, jincastle commented on books/tests.py
> +TestCase.maxDiff = None
필요없는 코드 정리 했습니다

2021-12-20 04:06 UTC, jincastle commented on books/views.py
> +            JsonResponse({"message" : "TYPE_ERROR"}, status=401)
정말 너무 감사합니다. ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2021-12-20 09:11 UTC, lordmyshepherd commented
offline code-review
```python
from django.views           import View
from django.http.response   import JsonResponse
from django.db.models.query import Prefetch
from django.db.models       import Avg 

from .models                import Book
from orders.models          import OrderItem
from core.decorator         import login_required

class BookView(View):
    @login_required
    def get(self, request, book_id):
        try:
            book = Book.objects.annotate(
                review_avg   = Avg('review'),
                is_purchased = Case(when(Q(orderitem_set__is_null=True, order__user=user), then=False), default = True))
            ).prefetch_related('authorbook_set__author').get(id=book_id)

            results = {
                "purchased"  : book.is_purchased
                "name"       : book.name,
                "price"      : book.price,
                "description": book.description,
                "thumbnail"  : book.thumbnail,
                "average"    : book.review_avg,
                "authors"    : [author.author.name for author in book.authorbook_set.all()]
            }

            return JsonResponse({"result":result}, status=200)

        except Book.DoesNotExist:
            JsonResponse({"message" : "DOES_NOT_EXIST"}, status=401)
```

2021-12-21 05:18 UTC, lordmyshepherd commented
LGTM 👍🏻

2021-12-21 05:19 UTC, merged