[add]main-order-book-view
wecode-bootcamp-korea/27-2nd-ReadyBooks-backend pull request #18
Opened 2021-12-19 06:10 UTC by SeongJongHo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인뷰에서 해당유저가 구매한 책들을 보여줄때 구매한 책들의 정보를 보내줌

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인한 유저가 구매한 책정보 프론트에 전달
2. 구매한 책이 없을경우 빈배열로 반환
2. 테스트 성공

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 어떤 model에서 시작점으로 잡아야 할지 고민을 오래함

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-20 03:20 UTC, lordmyshepherd requested changes

2021-12-20 03:20 UTC, lordmyshepherd commented on books/tests.py
> +        )
bulk_create()로 변경해서 실행 속도를 높여주세요~

2021-12-20 03:20 UTC, lordmyshepherd commented on books/views.py
> +        return JsonResponse({"result":result}, status=200 )
정확히는 책 정보라기 보다는 주문한 상품 목록을 요청하는 엔드포인트가 맞는 것 같습니다.
orderitem 컬렘이 있는 정보도 반환해주도록 구조를 수정해주세요!

2021-12-20 06:11 UTC, SeongJongHo commented on books/views.py
> +        return JsonResponse({"result":result}, status=200 )
```python
{
    "id" : item.id,
    "order_id" : "item.order.id,
    "book" : {
        "id",
        "name",
     }
}
```

2021-12-20 11:03 UTC, SeongJongHo commented on books/tests.py
> +        )
수정했습니다!

2021-12-20 11:04 UTC, SeongJongHo commented on books/views.py
> +        return JsonResponse({"result":result}, status=200 )
수정했습니다!

2021-12-21 05:19 UTC, lordmyshepherd commented
컨플릭트 해결 부탁드려요~

2021-12-21 09:26 UTC, lordmyshepherd commented
LGTM 👍🏻

2021-12-21 09:27 UTC, merged