[ADD] 장바구니 기능구현
wecode-bootcamp-korea/27-2nd-ReadyBooks-backend pull request #23
Opened 2021-12-22 06:32 UTC by Joshua-sung

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-장바구니에 담고 담아둔 물품을 보여주고 삭제

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.장바구니에 상품을 담을수있습니다.
2.장바구니에서 담은 상품을 볼수있습니다.
3.장바구니에 담긴 상품을 삭제할수 있습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
프론트엔드와 소통을 많이 하면서 배웠습니다.
<br />

## :: 기타 질문 및 특이 사항

2021-12-22 07:50 UTC, lordmyshepherd requested changes

2021-12-22 07:50 UTC, lordmyshepherd commented on carts/views.py
> +                return JsonResponse({"message" : "SUCCESS"}, status=201)
```suggestion
           if not Cart.objects.filter(user = user, book_id = book_id).exists():
               Cart.objects.create(user = user, book_id = book_id)
               return JsonResponse({"message" : "SUCCESS"}, status=201)
               
           return JsonResponse({"message" : "BOOK_ALREADY_EXIST"}, status=400)
                     
```

2021-12-22 07:50 UTC, lordmyshepherd commented on carts/views.py
> +        carts = Cart.objects.prefetch_related('book__authorbook_set__author').filter(user=user).order_by('-created_at')
```suggestion
        carts = Cart.objects.prefetch_related('book__authorbook_set__author').filter(user=request.user).order_by('-created_at')
```

2021-12-22 07:50 UTC, lordmyshepherd commented on carts/views.py
> +        user  = request.user
```suggestion
```

2021-12-22 07:50 UTC, lordmyshepherd commented on carts/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"}, status=400)
```suggestion
    def delete(self, request):
        Cart.objects.filter(id__in = request.GET.get("cart_ids"), user = request.user).delete()            
        return JsonResponse({"message" : "NO_CONTENTS"}, status=204)
```

2021-12-23 06:07 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-23 06:07 UTC, lordmyshepherd commented on carts/views.py
> +
빈 줄 지워주세요!

2021-12-23 06:27 UTC, Joshua-sung commented on carts/views.py
> +
수정했습니다 :)

2021-12-23 06:59 UTC, bigfanoftim approved these changes
LGTM 👍

2021-12-23 07:00 UTC, merged